version: "3.8"

services:
  # Banco de dados MySQL
  db:
    image: mariadb:10.4
    container_name: challenge-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: challenge_bry_tecnologia
      MYSQL_USER: bry_user
      MYSQL_PASSWORD: bry_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Backend Laravel
  backend:
    build: ./backend
    container_name: challenge-backend
    restart: always
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: challenge_bry_tecnologia
      DB_USERNAME: bry_user
      DB_PASSWORD: bry_pass
    volumes:
      - ./backend:/var/www/html

  # Frontend Angular
  frontend:
    build: ./frontend
    container_name: challenge-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  db_data:
